### ISSUE TITLE
Suggestion: Rifts

### ISSUE THREAD

**Issue by Tyrius1** [Sarinsa/Apocalypse-Rebooted#1]
After entering the nether random rifts will open on the overworld surface, pooring through it x amount of mobs. Where the mobs could be determined based on the config. Allowing for adding modded mobs like mcdoom and nethercraft mobs in addition to the classic wither skeles and magma slimes.

**Comment by Sarinsa** [comment]
Interesting stuff! I'll definitely come back to this

**Comment by Sarinsa** [comment]
Likely wont do anything with this. May come back here in the future, but for now Ill put it on ice
