### ISSUE TITLE
[1.19.2] ConcurrentModificationException during Client Setup

### ISSUE THREAD

**Issue by Thelnfamous1** [Sarinsa/Apocalypse-Rebooted#10]
[crash-2023-04-04_23.44.33-fml.txt](https://github.com/Sarinsa/Apocalypse-Rebooted/files/11155277/crash-2023-04-04_23.44.33-fml.txt)

This particular line is the causing the problem in the crash above. https://github.com/Sarinsa/Apocalypse-Rebooted/blob/4385a1f7c035b281446788a9bb14659408203998/src/main/java/com/toast/apocalypse/client/ClientRegister.java#L50

When adding things to vanilla maps during modloading, you need to be careful as that can cause this specific exception to be thrown.

Simple fix is to use the `enqueueWork` method from `FMLClientSetupEvent`, and call `ItemModelProps#register` inside the `Runnable` instance passed into it.

**Comment by Sarinsa** [comment]
Oh shoot, thats a silly overlook! Thank you for letting me know!
