### ISSUE TITLE
[Bug] Difficulty bar conflicts with boss bar

### ISSUE THREAD

**Issue by BugmanBugman** [Sarinsa/Apocalypse-Rebooted#11]
![2023-05-11_20 06 50](https://github.com/Sarinsa/Apocalypse-Rebooted/assets/40730042/38ab8535-8f82-451f-b1f9-9a7e88fe70da)
I dunno how y'all would wanna fix it, but I was thinking of what if you made the difficulty checker an item instead of a gui thing, idk though

**Comment by SkyGhostK** [comment]
You can change the position of the dificulty text modifing the file apocalypse-client in your .minecraft > config folder

**Comment by Sarinsa** [comment]
^^ Can be tweaked in the client config
