### ISSUE TITLE
Server Issue: Index 0 out of bounds for lengt 0 

### ISSUE THREAD

**Issue by Otherion1** [Sarinsa/Apocalypse-Rebooted#12]
### Main Issue
Whenever you try to enter on a server with the mod on, it instantly disconnects, with this error:
![image_2024-06-14_170302141](https://github.com/Sarinsa/Apocalypse-Rebooted/assets/99122497/a14fe4f4-27be-478b-9ab8-459b833d3bf6)

On the server it just says that the user disconnected, and on the client log, the only line referencing the error is this one:
`[14jun2024 17:03:17.616] [Netty Client IO #1/ERROR] [net.minecraftforge.network.NetworkRegistry/NETREGISTRY]: Channels [apocalypse:channel] rejected vanilla connections`

No other mods on the client or server, just Apocalypse and Forge.

### Mod list

Forge-1.20.1-47.2.17
Apocalypse-Rebooted-1.20.1-1.3.5-r

### System information

Windows 10
Processor CPU AMD Ryzen 5 3600
NVIDIA GeForce RTX 3070
16 gb ram _(2 gb assigned)_

**Comment by Sarinsa** [comment]
Seems to be an issue with the mod's network channel, I should be able to roll out a fix today

**Comment by Sarinsa** [comment]
Scrap that, looks like it is a recipe serializer issue

**Comment by Sarinsa** [comment]
This has now been fixed
