### ISSUE TITLE
Suggestion: Plague Carrier

### ISSUE THREAD

**Issue by Tyrius1** [Sarinsa/Apocalypse-Rebooted#2]
Imagine a big fat abomination that walks around oozing a poison aura. It could occasionally spit poison. As an additional interaction, if there are zombies nearby it could attempt to grab and drag the player for a short duration in attempts to bring the player towards the nearby zombies.

**Comment by Sarinsa** [comment]
Likely wont do anything with this. Putting it on ice for now.
