### ISSUE TITLE
Howling Moon

### ISSUE THREAD

**Issue by Tyrius1** [Sarinsa/Apocalypse-Rebooted#3]
The most iconic Full Moon related mob.. The Werewolf. Climbing walls, running fast and jumping extra high, these mobs have 0 issues scaling your defenses and have even less issues eating you for dinner.
Werewolves claws are incredibly strong and can be used to make a set of gauntlets.
equipped via curios in the hand slot. It could allow for climbing walls.

**Comment by Sarinsa** [comment]
There will be a new wolf mob in the new version of the mod, so Ill see if I can merge some of the features suggested here into it. A gadget for climbing could be interesting
