### ISSUE TITLE
Suggestion: Raiders

### ISSUE THREAD

**Issue by Tyrius1** [Sarinsa/Apocalypse-Rebooted#4]
During an apocalypse there could be more than just crazy scary monsters that come hunting you down. Very likely it will be your fellow man! Not illagers, not villagers, just angry lost players. Some by themselves. Some in packs! They can open wooden doors, wooden trap doors and climb ladders! They will steal from your chests and loot your dead corpse (if corpse mod is also installed).

**Comment by Sarinsa** [comment]
Probably wont end up doing anything with this. Putting it on ice for now
