### ISSUE TITLE
Suggestion: Full Moon Sleeping

### ISSUE THREAD

**Issue by Tyrius1** [Sarinsa/Apocalypse-Rebooted#6]
a config to prevent players from sleeping to prevent or avoid the full moon event.

**Comment by Sarinsa** [comment]
Players should already be unable to sleep on full moons. Are you able to?

**Comment by Tyrius1** [comment]
>.< my bad forgot i removed from server while during previous crash. It is indeed preventing me from sleeping lol Thanks! 👍
