### ISSUE TITLE
Suggestions - Nukelord

### ISSUE THREAD

**Issue by NukelordPvP** [Sarinsa/Apocalypse-Rebooted#9]
Add:
Night events into a different mod maybe.
Darkwood implemented them very well
https://www.youtube.com/watch?v=A1E0UvcZhcQ

Change:
ghosts to have a counter (block, item or something to keep them away)
ghosts doing damage maybe make them not deal damage and instead be support (throw slowness and snowballs to annoy you (debuffs should be configurable). 
entire mod should pause if player loading the chunks is afk to keep mob farms functional
Increase screech sound volume enough that you can hear it from deep underground (BNW2 ground is 128 blocks deep)

**Comment by Sarinsa** [comment]
No longer maintaining 1.16.5 branch, closing
